#!/bin/bash
#SBATCH --job-name=TCN_train
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=1-12:00:00
#SBATCH --output=logs/tcn_%j.out
#SBATCH --error=logs/tcn_%j.err
#SBATCH --mail-type=begin,end,fail,requeue
#SBATCH --mail-user=jam4gd@umsystem.edu

# Env Setup

module purge
module load anaconda

# Directory Setup

mkdir -p logs
mkdir -p tcn_outputs

# Run training

python main.py